language: python
env:
  - TOXENV=pytest28
  - TOXENV=pytest29
matrix:
  include:
    - python: 2.7
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=flake8
install:
  - pip install tox-travis
script:
  - tox
